CREATE TABLE LOCATION (
    LOCATION_ID INTEGER NOT NULL AUTO_INCREMENT,
    LOCATION_NAME VARCHAR(128) NOT NULL,
    LATITUDE DECIMAL (13,8) NOT NULL,
    LONGITUDE DECIMAL (13,8) NOT NULL,
    LOCATION_TYPE INTEGER NOT NULL,
    PARENT_LOCATION_ID INTEGER,
    PRIMARY KEY(LOCATION_ID)
);

CREATE TABLE MALL (
    MALL_ID   INTEGER NOT NULL AUTO_INCREMENT,
    MALL_NAME VARCHAR (128) NOT NULL,
    LOCATION_ID INTEGER NOT NULL,
    PRIMARY KEY(MALL_ID)
);

ALTER TABLE MALL ADD CONSTRAINT MALL_LOCATION_FK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID);

CREATE TABLE STORE (
    STORE_ID     INTEGER NOT NULL AUTO_INCREMENT,
    STORE_NAME  VARCHAR (128) NOT NULL,
    LOCATION_ID INTEGER NOT NULL,
    MALL_ID INTEGER,
    ADDRESS      VARCHAR (256) NOT NULL,
    PHONE_NUMBER VARCHAR (128) NOT NULL,
    PRIMARY KEY(STORE_ID)
);

ALTER TABLE STORE ADD CONSTRAINT STORE_LOCATION_FK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID);

ALTER TABLE STORE ADD CONSTRAINT STORE_MALL_FK FOREIGN KEY (MALL_ID) REFERENCES MALL(MALL_ID);

CREATE TABLE CATEGORY (
    CATEGORY_ID        INTEGER NOT NULL AUTO_INCREMENT,
    CATEGORY_NAME      VARCHAR (128) NOT NULL,
    PARENT_CATEGORY_ID INTEGER,
    PRIMARY KEY(CATEGORY_ID)
);

ALTER TABLE CATEGORY ADD CONSTRAINT CATEGORY_PARENT_CATEGORY_FK FOREIGN KEY (PARENT_CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID);

CREATE TABLE PRODUCT (
    PRODUCT_ID   INTEGER NOT NULL AUTO_INCREMENT,
    PRODUCT_NAME VARCHAR (128) NOT NULL,
    CATEGORY_ID INTEGER NOT NULL,
    PRIMARY KEY(PRODUCT_ID)
);

ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_CATEGORY_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID);

CREATE TABLE BRAND (
    BRAND_ID     INTEGER NOT NULL AUTO_INCREMENT,
    BRAND_NAME   VARCHAR (128) NOT NULL,
    PRIMARY KEY(BRAND_ID)
);

CREATE TABLE SALE (
    SALE_ID INTEGER NOT NULL AUTO_INCREMENT,
    STORE_ID INTEGER NOT NULL,
    OFFER NVARCHAR (1024) NOT NULL,
    START_DATE DATE,
    END_DATE   DATE,
    PRIMARY KEY(SALE_ID)
);

ALTER TABLE SALE ADD CONSTRAINT SALE_STORE_FK FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID);

CREATE TABLE SALE_PRODUCT_OFFER (
    OFFER_ID   INTEGER NOT NULL AUTO_INCREMENT,
    SALE_ID    INTEGER NOT NULL,
    PRODUCT_ID INTEGER,
    BRAND_ID INTEGER,
    OFFER NVARCHAR (1024) NOT NULL,
    START_DATE DATE,
    END_DATE   DATE,
    PRIMARY KEY(OFFER_ID)
);

ALTER TABLE SALE_PRODUCT_OFFER ADD CONSTRAINT SPO_SALE_FK FOREIGN KEY (SALE_ID) REFERENCES SALE(SALE_ID);

ALTER TABLE SALE_PRODUCT_OFFER ADD CONSTRAINT SPO_PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID);

ALTER TABLE SALE_PRODUCT_OFFER ADD CONSTRAINT SPO_BRAND_FK FOREIGN KEY (BRAND_ID) REFERENCES BRAND(BRAND_ID);
